image: Ubuntu

stack: jdk 1.8
branches:
  only:
    - master

build: off

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-card-delivery.jar &


build_script:
  - ./gradlew test --info "-Dselenide.headless=true"